/* DO NOT EDIT THIS FILE */

#ifndef INCLUDE_VIEWER_H_
#define INCLUDE_VIEWER_H_

#include "sinoscope.h"

int viewer_init(sinoscope_t* sinoscope);
void viewer_destroy();
int viewer_open();

#endif /* INCLUDE_VIEWER_H_ */