/* DO NOT EDIT THIS FILE */

#include <png.h>
#include <stdlib.h>
#include <unistd.h>

#include "image.h"
#include "log.h"

image_t* image_create(size_t width, size_t height) {
    image_t* image = calloc(1, sizeof(*image));
    if (image == NULL) {
        LOG_ERROR_ERRNO("calloc");
        goto fail_exit;
    }

    image->width  = width;
    image->height = height;

    image->pixels = malloc((image->width * image->height) * sizeof(*image->pixels));
    if (image->pixels == NULL) {
        LOG_ERROR_ERRNO("malloc");
        goto fail_free_image;
    }

    return image;

fail_free_image:
    free(image);
fail_exit:
    return NULL;
}

void image_destroy(image_t* image) {
    if (image->pixels != NULL) {
        free(image->pixels);
    }
    free(image);
}

int image_save_png(image_t* image, char* filename) {
    if (image == NULL || filename == NULL) {
        LOG_ERROR_NULL_PTR();
        goto fail_exit;
    }

    /* source: https://gist.github.com/niw/5963798 */

    FILE* file = fopen(filename, "wb");
    if (file == NULL) {
        LOG_ERROR_ERRNO("fopen");
        goto fail_exit;
    }

    png_structp png = png_create_write_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
    if (png == NULL) {
        LOG_ERROR("couldn't create png_struct");
        goto fail_close_file;
    }

    png_infop info = png_create_info_struct(png);
    if (info == NULL) {
        LOG_ERROR("couldn't create png_infop");
        goto fail_free_png_struct;
    }

    if (setjmp(png_jmpbuf(png))) {
        goto fail_free_png_info;
    }

    png_init_io(png, file);

    /* output is 8 bit depth, RGBA format */

    png_set_IHDR(png, info, image->width, image->height, 8, PNG_COLOR_TYPE_RGBA, PNG_INTERLACE_NONE,
                 PNG_COMPRESSION_TYPE_DEFAULT, PNG_FILTER_TYPE_DEFAULT);

    png_write_info(png, info);

    /* copy image data */

    png_bytep* row_pointers = calloc(image->height, sizeof(*row_pointers));
    if (row_pointers == NULL) {
        goto fail_free_png_struct;
    }

    for (int j = 0; j < image->height; j++) {
        row_pointers[j] = malloc(png_get_rowbytes(png, info));
        if (row_pointers[j] == NULL) {
            goto fail_free_rows;
        }
    }

    for (int j = 0; j < image->height; j++) {
        for (int i = 0; i < image->width; i++) {
            pixel_t* pixel             = image_get_pixel(image, i, j);
            row_pointers[j][4 * i + 0] = pixel->bytes[0];
            row_pointers[j][4 * i + 1] = pixel->bytes[1];
            row_pointers[j][4 * i + 2] = pixel->bytes[2];
            row_pointers[j][4 * i + 3] = 255;
        }
    }

    /* write PNG file */

    png_write_image(png, row_pointers);
    png_write_end(png, NULL);

    /* cleanup */

    for (int j = 0; j < image->height; j++) {
        if (row_pointers[j] != NULL) {
            free(row_pointers[j]);
        }
    }
    free(row_pointers);

    png_destroy_write_struct(&png, &info);
    fclose(file);

    return 0;

fail_free_rows:
    for (int j = 0; j < image->height; j++) {
        if (row_pointers[j] != NULL) {
            free(row_pointers[j]);
        }
    }
    free(row_pointers);
fail_free_png_info:
    png_destroy_write_struct(&png, &info);
    goto fail_close_file;
fail_free_png_struct:
    png_destroy_write_struct(&png, NULL);
fail_close_file:
    fclose(file);
fail_exit:
    return -1;
}
