/* DO NOT EDIT THIS FILE */

#include <stdio.h>
#include <stdlib.h>

#include "cart.h"
#include "grid.h"
#include "log.h"

static unsigned int* create_dimensions(unsigned int total_dimension, unsigned int count) {
    unsigned int* dimensions = malloc(count * sizeof(*dimensions));
    if (dimensions == NULL) {
        LOG_ERROR_ERRNO("malloc");
        goto fail_exit;
    }

    unsigned int quotient  = total_dimension / count;
    unsigned int remainder = total_dimension % count;

    for (int i = 0; i < count; i++) {
        unsigned int value = quotient;

        /* distribute the remainder, total must equal total_dimension */
        if (remainder > 0) {
            remainder--;
            value++;
        }

        dimensions[i] = value;
    }

    return dimensions;

fail_exit:
    return NULL;
}

static unsigned int* create_offsets(unsigned int* dimensions, unsigned int count) {
    unsigned int* offsets = malloc(count * sizeof(*offsets));
    if (offsets == NULL) {
        LOG_ERROR_ERRNO("malloc");
        goto fail_exit;
    }

    offsets[0] = 0;
    for (int i = 1; i < count; i++) {
        offsets[i] = offsets[i - 1] + dimensions[i - 1];
    }

    return offsets;

fail_exit:
    return NULL;
}

cart2d_t* cart2d_create(unsigned int grid_x, unsigned int grid_y, unsigned int width, unsigned int height) {
    cart2d_t* cart = malloc(sizeof(*cart));
    if (cart == NULL) {
        LOG_ERROR_ERRNO("malloc");
        goto fail_exit;
    }

    cart->grid_x_count = grid_x;
    cart->grid_y_count = grid_y;
    cart->total_width  = width;
    cart->total_height = height;

    cart->x_dims = create_dimensions(width, grid_x);
    if (cart->x_dims == NULL) {
        LOG_ERROR("failed to create X dimensions");
        goto fail_exit;
    }

    cart->y_dims = create_dimensions(height, grid_y);
    if (cart->y_dims == NULL) {
        LOG_ERROR("failed to create Y dimensions");
        goto fail_free_cart_x_dims;
    }

    cart->x_offsets = create_offsets(cart->x_dims, grid_x);
    if (cart->x_offsets == NULL) {
        LOG_ERROR("failed to create X offsets");
        goto fail_free_cart_y_dims;
    }

    cart->y_offsets = create_offsets(cart->y_dims, grid_y);
    if (cart->x_offsets == NULL) {
        LOG_ERROR("failed to create Y offsets");
        goto fail_free_cart_x_offsets;
    }

    cart->grids = calloc(sizeof(*cart->grids), grid_y);
    if (cart->grids == NULL) {
        LOG_ERROR_ERRNO("calloc");
        goto fail_free_cart_y_offsets;
    }

    for (int j = 0; j < cart->grid_y_count; j++) {
        cart->grids[j] = calloc(sizeof(*cart->grids[j]), grid_x);
        if (cart->grids[j] == NULL) {
            LOG_ERROR_ERRNO("calloc");
            goto fail_free_cart_grids;
        }

        for (int i = 0; i < cart->grid_x_count; i++) {
            cart->grids[j][i] = grid_create(cart->x_dims[i], cart->y_dims[j], 0);
            if (cart->grids[j][i] == NULL) {
                LOG_ERROR("failed to create grid");
                goto fail_free_cart_grids;
            }
        }
    }

    return cart;

fail_free_cart_grids:
    for (int j = 0; j < cart->grid_y_count; j++) {
        if (cart->grids[j] == NULL) {
            continue;
        }

        for (int i = 0; i < cart->grid_x_count; i++) {
            if (cart->grids[j][i] == NULL) {
                continue;
            }

            grid_destroy(cart->grids[j][i]);
        }

        free(cart->grids[j]);
    }
    free(cart->grids);
fail_free_cart_y_offsets:
    free(cart->y_offsets);
fail_free_cart_x_offsets:
    free(cart->x_offsets);
fail_free_cart_y_dims:
    free(cart->y_dims);
fail_free_cart_x_dims:
    free(cart->x_dims);
fail_exit:
    return NULL;
}

void cart2d_destroy(cart2d_t* cart) {
    for (int j = 0; j < cart->grid_y_count; j++) {
        for (int i = 0; i < cart->grid_x_count; i++) {
            grid_destroy(cart->grids[j][i]);
        }

        free(cart->grids[j]);
    }

    free(cart->grids);
    free(cart->x_dims);
    free(cart->y_dims);
    free(cart->x_offsets);
    free(cart->y_offsets);
    free(cart);
}

grid_t* cart2d_get_grid(cart2d_t* cart, unsigned int x, unsigned int y) {
    if (cart == NULL || x >= cart->grid_x_count || y >= cart->grid_y_count) {
        LOG_ERROR("invalid input arguments");
        goto fail_exit;
    }

    return cart->grids[y][x];

fail_exit:
    return NULL;
}

int cart2d_set_grid(cart2d_t* cart, unsigned int x, unsigned int y, grid_t* grid) {
    if (cart == NULL || x >= cart->grid_x_count || y >= cart->grid_y_count) {
        LOG_ERROR("invalid input arguments");
        goto fail_exit;
    }

    cart->grids[y][x] = grid;

    return 0;

fail_exit:
    return -1;
}

cart2d_t* cart2d_from_grid(grid_t* grid, unsigned int grid_x, unsigned int grid_y) {
    if (grid == NULL) {
        LOG_ERROR_NULL_PTR();
        goto fail_exit;
    }

    cart2d_t* cart = cart2d_create(grid_x, grid_y, grid->width, grid->height);
    if (cart == NULL) {
        LOG_ERROR("failed to create cart");
        goto fail_exit;
    }

    for (int j = 0; j < cart->grid_y_count; j++) {
        for (int i = 0; i < cart->grid_x_count; i++) {
            grid_t* dst_grid = cart2d_get_grid(cart, i, j);
            if (dst_grid == NULL) {
                LOG_ERROR("failed to get grid");
                goto fail_destroy_cart;
            }

            unsigned int x_offset = cart->x_offsets[i];
            unsigned int y_offset = cart->y_offsets[j];
            unsigned int x_size   = cart->x_dims[i];
            unsigned int y_size   = cart->y_dims[j];

            if (grid_copy_block(grid, x_offset, y_offset, x_size, y_size, dst_grid, 0, 0) < 0) {
                LOG_ERROR("failed to copy grid block");
                goto fail_destroy_cart;
            }
        }
    }

    return cart;

fail_destroy_cart:
    cart2d_destroy(cart);
fail_exit:
    return NULL;
}

grid_t* cart2d_to_grid(cart2d_t* cart) {
    if (cart == NULL) {
        LOG_ERROR_NULL_PTR();
        goto fail_exit;
    }

    grid_t* grid = grid_create(cart->total_width, cart->total_height, 0);
    if (grid == NULL) {
        LOG_ERROR("failed to create grid");
        goto fail_exit;
    }

    for (int j = 0; j < cart->grid_y_count; j++) {
        for (int i = 0; i < cart->grid_x_count; i++) {
            grid_t* src_grid = cart2d_get_grid(cart, i, j);
            if (src_grid == NULL) {
                LOG_ERROR("failed to get grid");
                goto fail_destroy_grid;
            }

            unsigned int x_size   = cart->x_dims[i];
            unsigned int y_size   = cart->y_dims[j];
            unsigned int x_offset = cart->x_offsets[i];
            unsigned int y_offset = cart->y_offsets[j];

            if (grid_copy_block(src_grid, 0, 0, x_size, y_size, grid, x_offset, y_offset) < 0) {
                LOG_ERROR("failed to copy grid block");
                goto fail_destroy_grid;
            }
        }
    }

    return grid;

fail_destroy_grid:
    grid_destroy(grid);
fail_exit:
    return NULL;
}

int cart2d_padding(cart2d_t* cart, int padding) {
    if (cart == NULL) {
        LOG_ERROR_NULL_PTR();
        goto fail_exit;
    }

    for (int j = 0; j < cart->grid_y_count; j++) {
        for (int i = 0; i < cart->grid_x_count; i++) {
            grid_t* grid = cart2d_get_grid(cart, i, j);
            if (grid == NULL) {
                LOG_ERROR("failed to get grid");
                goto fail_exit;
            }

            grid_t* new_grid = grid_clone_with_padding(grid, padding);
            if (new_grid == NULL) {
                LOG_ERROR("failed to pad grid");
                goto fail_exit;
            }

            if (cart2d_set_grid(cart, i, j, new_grid) < 0) {
                LOG_ERROR("failed to set grid");
            }

            grid_destroy(grid);
        }
    }

    return 0;

fail_exit:
    return -1;
}
