/* DO NOT EDIT THIS FILE */

#include <limits.h>
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "heatsim.h"
#include "log.h"

static void show_help(FILE* f, const char* exec_name) {
    fprintf(f, "Usage: %s [OPTION]...\n", exec_name);
    fprintf(f, "\n");
    fprintf(f, "Options:\n");
    fprintf(f, "  --iterations N number of iterations to perform\n");
    fprintf(f, "  --dim-x N      x dimension of the computation\n");
    fprintf(f, "  --dim-y N      y dimension of the computation\n");
    fprintf(f, "  --input FILE   input image\n");
    fprintf(f, "  --output FILE  output file\n");
    fprintf(f, "  --help         show this help\n");
}

static void fail_missing_option(const char* exec_name, const char* opt) {
    fprintf(stderr, "%s: missing option '%s'\n", exec_name, opt);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_missing_argument(const char* exec_name, const char* opt) {
    fprintf(stderr, "%s: option '%s' requires an argument\n", exec_name, opt);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_unknown_argument(const char* exec_name, const char* opt) {
    fprintf(stderr, "%s: unrecognized option '%s'\n", exec_name, opt);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_number_conversion(const char* exec_name, const char* num, const char* opt) {
    fprintf(stderr, "%s: could not convert number '%s' for option '%s'\n", exec_name, num, opt);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_negative_arg(const char* exec_name, const char* opt, const char* arg) {
    fprintf(stderr, "%s: option '%s' requires positive number, got '%s'\n", exec_name, opt, arg);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

void convert_and_set_positive_arg(const char* exec_name, const char* opt, const char* arg, unsigned int* result) {
    long int number = strtol(arg, NULL, 10);
    if (number == LONG_MIN || number == LONG_MAX) {
        fail_number_conversion(exec_name, opt, arg);
    }

    if (number <= 0) {
        fail_negative_arg(exec_name, opt, arg);
    }

    *result = number;
}

int main(int argc, char* argv[]) {
    char* exec_name         = argv[0];
    char* input_file        = NULL;
    char* output_file       = NULL;
    unsigned int iterations = 110;
    unsigned int dim_x      = 1;
    unsigned int dim_y      = 1;

    int status = MPI_Init(&argc, &argv);
    if (status != MPI_SUCCESS) {
        LOG_ERROR_MPI("MPI_Init", status);
        exit(1);
    }

    status = MPI_Comm_set_errhandler(MPI_COMM_WORLD, MPI_ERRORS_RETURN);
    if (status != MPI_SUCCESS) {
        LOG_ERROR_MPI("MPI_Errhandler_set", status);
        exit(1);
    }

    for (int i = 1; i < argc; i++) {
        if (strcmp("--iterations", argv[i]) == 0) {
            if (i > argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            convert_and_set_positive_arg(exec_name, argv[i], argv[i + 1], &iterations);
            i++;
        } else if (strcmp("--dim-x", argv[i]) == 0) {
            if (i > argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            convert_and_set_positive_arg(exec_name, argv[i], argv[i + 1], &dim_x);
            i++;
        } else if (strcmp("--dim-y", argv[i]) == 0) {
            if (i > argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            convert_and_set_positive_arg(exec_name, argv[i], argv[i + 1], &dim_y);
            i++;
        } else if (strcmp("--input", argv[i]) == 0) {
            if (i > argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            input_file = argv[++i];
        } else if (strcmp("--output", argv[i]) == 0) {
            if (i > argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            output_file = argv[++i];
        } else if (strcmp("--help", argv[i]) == 0) {
            show_help(stdout, exec_name);
            exit(0);
        } else {
            fail_unknown_argument(exec_name, argv[i]);
        }
    }

    if (input_file == NULL) {
        fail_missing_option(exec_name, "--input");
    }

    char output_file_buffer[128];
    if (output_file == NULL) {
        output_file = output_file_buffer;
        if (snprintf(output_file_buffer, 128, "%s.output.png", input_file) >= 127) {
            LOG_ERROR("failed to format output filename");
            exit(1);
        }
    }

    printf("configurations:\n");
    printf(" - %u iterations\n", iterations);
    printf(" - %u node%s in X\n", dim_x, (dim_x == 1) ? "" : "s");
    printf(" - %u node%s in Y\n", dim_y, (dim_x == 1) ? "" : "s");
    printf(" - input file is '%s'\n", input_file);
    printf(" - output file is '%s'\n", output_file);

    if (heatsim_run(input_file, output_file, dim_x, dim_y, iterations) < 0) {
        LOG_ERROR("failed to run simulation");
        exit(1);
    }

    status = MPI_Finalize();
    if (status != MPI_SUCCESS) {
        LOG_ERROR_MPI("MPI_Finalize", status);
        exit(1);
    }

    return 0;
}
