/* DO NOT EDIT THIS FILE */

#ifndef INCLUDE_CART_H_
#define INCLUDE_CART_H_

#include "grid.h"

typedef struct cart2d {
    grid_t*** grids;

    /* number of blocks in x/y dimensions */
    unsigned int grid_x_count;
    unsigned int grid_y_count;

    /* total dimension */
    unsigned int total_width;
    unsigned int total_height;

    /* x/y dimensions of each column/row respectively */
    unsigned int* x_dims;
    unsigned int* y_dims;

    /* x/y offsets of each column/row respectively */
    unsigned int* x_offsets;
    unsigned int* y_offsets;
} cart2d_t;

cart2d_t* cart2d_create(unsigned int grid_x, unsigned int grid_y, unsigned int width, unsigned int height);
void cart2d_destroy(cart2d_t* cart);

grid_t* cart2d_get_grid(cart2d_t* cart, unsigned int x, unsigned int y);
int cart2d_set_grid(cart2d_t* cart, unsigned int x, unsigned int y, grid_t* grid);

cart2d_t* cart2d_from_grid(grid_t* grid, unsigned int grid_x, unsigned int grid_y);
grid_t* cart2d_to_grid(cart2d_t* cart);

int cart2d_padding(cart2d_t* cart, int padding);

#endif /* INCLUDE_CART_H_ */
