/* DO NOT EDIT THIS FILE */

#ifndef COLOR_H_
#define COLOR_H_

#include "pixel.h"

unsigned int color_get_interval(double max);
double color_get_interval_inverted(double max);
void color_value(pixel_t* pixel, double value, double max);

#endif /* COLOR_H_ */
