/* DO NOT EDIT THIS FILE */

#ifndef INCLUDE_HEAT_H_
#define INCLUDE_HEAT_H_

#include <mpi.h>

#include "cart.h"
#include "grid.h"

typedef struct heatsim {
    MPI_Comm communicator;
    int rank_count;
    int rank;
    int rank_north_peer;
    int rank_south_peer;
    int rank_east_peer;
    int rank_west_peer;
    int coordinates[2];
} heatsim_t;

int heatsim_diffuse(grid_t* current, grid_t* next);
int heatsim_run(char* input, char* output, unsigned int dim_x, unsigned int dim_y, unsigned int iterations);

int heatsim_init(heatsim_t* heatsim, unsigned int x, unsigned int y);
int heatsim_send_grids(heatsim_t* heatsim, cart2d_t* cart);
grid_t* heatsim_receive_grid(heatsim_t* heatsim);
int heatsim_exchange_borders(heatsim_t* heatsim, grid_t* grid);
int heatsim_send_result(heatsim_t* heatsim, grid_t* grid);
int heatsim_receive_results(heatsim_t* heatsim, cart2d_t* cart);

#endif /* INCLUDE_HEAT_H_ */
