/* DO NOT EDIT THIS FILE */

#ifndef INCLUDE_LOG_H_
#define INCLUDE_LOG_H_

#include <errno.h>
#include <stdio.h>
#include <string.h>

#define LOG_ERROR(msg, args...) fprintf(stderr, "%s@%d: " msg "\n", __FILE__, __LINE__, ##args)
#define LOG_ERROR_ERRNO(msg) LOG_ERROR("%s (%s)", msg, strerror(errno))
#define LOG_ERROR_NULL_PTR(...) LOG_ERROR("NULL pointer received")
#define LOG_ERROR_MPI(msg, code)                    \
    do {                                            \
        char buffer[MPI_MAX_ERROR_STRING];          \
        int resultlen;                              \
        MPI_Error_string(code, buffer, &resultlen); \
        LOG_ERROR("%s (%s)", msg, buffer);          \
    } while (0)

#endif /* INCLUDE_LOG_H_ */
