/* DO NOT EDIT THIS FILE */

#ifndef INCLUDE_PIXEL_H_
#define INCLUDE_PIXEL_H_

typedef struct pixel {
    unsigned char bytes[4];
} pixel_t;

static const pixel_t pixel_white = {.bytes = {255, 255, 255, 255}};
static const pixel_t pixel_black = {.bytes = {0, 0, 0, 255}};

#endif /* INCLUDE_PIXEL_H_ */
